version: "3"
services:
  postgres:
    container_name: postgres
    env_file: ./.env
    image: postgres
    volumes:
      - bobJoyingDBVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}

  bobjoying_app:
    container_name: bobjoying_app
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    volumes:
      - bobJoyingAppVolume:/tmp

  redis:
    container_name: redis
    env_file: ./.env
    image: redis
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    volumes:
      - bobJoyingRedisVolume:/data
    command: >
      --bind 0.0.0.0 --requirepass ${REDIS_PASSWORD}

volumes:
  bobJoyingDBVolume:
  bobJoyingAppVolume:
  bobJoyingRedisVolume:

