FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
WORKDIR /app
COPY build/libs/*.jar /app/app.jar
COPY /src/main/resources/application-docker.yml /app/application-docker.yml
COPY /src/main/resources/graphql /app/graphql
ENTRYPOINT ["java","-jar","app.jar", "--spring.config.location=/app/application-docker.yml"]
