FROM postgres

# 올바른 경로로 심볼릭 링크 생성 및 locale 설정
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo 'ko_KR.UTF-8 UTF-8' >> /etc/locale.gen && \
    locale-gen

# 환경 변수 설정
ENV LANG=ko_KR.UTF-8 \
    LC_COLLATE=ko_KR.UTF-8 \
    POSTGRES_INITDB_ARGS="--data-checksums"
