name: develop CI check on docker

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  checks: write
  pull-requests: write

env:
  SPRING_DOCKER_IMAGE: bobjoying_image:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: PostgreSQL 설치
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '16'
          postgresql db: 'bobjoying'
          postgresql user: 'postgres'
          postgresql password: '1234'

      - name: 환경변수 설정
        run: |
          touch ./.env
          echo "${{ secrets.DOCKER_COMPOSE_ENV }}" > ./.env
        shell: bash

      - name: properties 파일 생성
        run: |
          cd ./src/main
          mkdir resources
          cd resources
          touch ./application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
        shell: bash

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradle 실행 허가
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: docker build . -t bobjoying_image:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push bobjoying_image:latest

      - name: Build and run Docker containers
        run: |
          docker-compose up -d

      - name: 빌드 결과 Slack으로 알림
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,author,pullRequest # selectable (default: repo,message)
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: ` Docker CI 결과입니다\n 결과 : ${{ job.status }}\n repo: ${process.env.AS_REPO}\n author: ${process.env.AS_AUTHOR}\n PR: ${process.env.AS_PULL_REQUEST}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
